# ProBot Stale (https://probot.github.io/apps/stale/)

daysUntilStale: 90
daysUntilClose: 14
exemptLabels:
  - accepted
  - blocked
  - bug
  - enhancement
  - greenkeeper
  - 'help wanted'
  - meta
staleLabel: stale
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs.
closeComment: false
