browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  # https://github.com/airtap/sauce/issues/11
  # - name: safari
  #   version: latest
  - name: edge
    version: latest
  - name: and_chr
    version: latest
  - name: ios_saf
    version: latest
providers:
  - airtap-sauce
presets:
  local:
    providers: airtap-manual
    browsers:
      - name: manual
