browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  # https://github.com/airtap/sauce/issues/11
  # - name: safari
  #   version: latest
  - name: edge
    version: latest
  - name: and_chr
    version: latest
  - name: ios_saf
    version: latest
providers:
  - airtap-system
presets:
  local:
    providers: airtap-manual
    browsers:
      - name: manual
  sauce:
  # Not used yet pending https://github.com/SocketDev/wormhole-crypto/issues/5
  # and https://github.com/airtap/airtap/issues/311
    providers: airtap-sauce
browserify:
  - transform: babelify
    global: true
    presets: ['@babel/preset-env']
    plugins: ['@babel/plugin-syntax-import-assertions']
server: './scripts/browser-serve.js'
